### ISSUE TITLE
Logo contribution

### ISSUE THREAD

**Issue by reallinfo** [xyteam/xyPlatform#16]
Hi, I think this project does not have a logo. If you want, I would like to contribute to your project. Actually, I have an idea. Do you want to see?

**Comment by xywang68** [comment]
Please do.

**Comment by reallinfo** [comment]
i wanted to design a memorable, minimalist logo. I used blue as a technological color. What do you think?

![xyy](https://user-images.githubusercontent.com/36298335/54076304-4c6c6300-42bb-11e9-9e78-22eadcdfbc2d.jpg)


![xy](https://user-images.githubusercontent.com/36298335/54076227-44f88a00-42ba-11e9-95a3-0a6ddf3a7c7c.jpg)

**Comment by xywang68** [comment]
The main theme look nice. As to the xy logo itself, can it simplify more, just present a x with disconnected upper left and lower right, or just disconnected lower right. This way both xy are represented, and it appears standing firm. What do you think?

Xinyu
@gmail

**Comment by reallinfo** [comment]
Oh sorry, I don't fully understand. Could you please make a small sketch as an example?

**Comment by xywang68** [comment]
Here..something along this line. 


Xinyu
@gmail

**Comment by reallinfo** [comment]
I think you want something like that. But this is unfortunately not original.

![xy2](https://user-images.githubusercontent.com/36298335/54085235-bc76f980-434c-11e9-867e-709cf8c15b77.jpg)

Beacuse, I found an existing logo that looks like this.

![image](https://user-images.githubusercontent.com/36298335/54085229-acf7b080-434c-11e9-8730-2f296131e22f.png)

Also, I have tried a different combination. It also represents the functionality of the software. (code icon)

![xy3](https://user-images.githubusercontent.com/36298335/54085255-21caea80-434d-11e9-8f54-85a66f2253c5.jpg)

**Comment by reallinfo** [comment]
If you want
Also, I can also think of logo ideas that emphasize the functionality of the software.

**Comment by xywang68** [comment]
Code icon is interesting. Maybe we can use color contrast to make it stand out. As to the X icon, what if we make the top and bottom flat, would it become original?

Xinyu
@gmail

**Comment by xywang68** [comment]
More thoughts on the code icon, can we make that icon with 3 arms to extend as xy?

Xinyu
@gmail

**Comment by reallinfo** [comment]
I added 3 arms. Also, I highlighted the code icon with a different contrast. how does it look?

![xyyyy](https://user-images.githubusercontent.com/36298335/54090199-953b1f00-4382-11e9-870f-2a1918747b8d.jpg)

**Comment by xywang68** [comment]
Both are very good. I might like the second one a bit more. Thank you so much. 

Xinyu
@gmail

**Comment by reallinfo** [comment]
You're welcome. Do you want me to send a pr? I can also update the readme file.

**Comment by xywang68** [comment]
Please do. Thank you.

**Comment by reallinfo** [comment]
https://github.com/xyteam/xyPlatform/pull/17

**Comment by xywang68** [comment]
Thank you. The logo looked really nice with the README file.
Can you also create one for the xyTeam?

**Comment by reallinfo** [comment]
Ofcourse, Can you give me some information?

**Comment by xywang68** [comment]
Hi, mate, I don't know what to call you with. Thanks again for the logo contribution.
Regarding the background of xyTeam, initially I wanted to do a few automation related opensource project, and start asking a few folks to join the effort, and I need to give a name to the team. I thought of xy as my name initial, but when it carry over to coding it sounds and looks cool, so I call gave the name as xyTeam. The folks like it, so I settled with this name.
If you looked into my team, you will see the AutoBDD project. This is the main project the xyTeam mates are working on.
So this the the background.
If you could. it would be nice to contribute logos for the xyTeam and for the AutoBDD project. Really appreciated.
